create table devices (
    id bigint generated by default as identity,
    created_date timestamp,
    status varchar(255),
    last_modified_date timestamp,
    description varchar(255),
    firmware_version varchar(255),
    ip_address varchar(255),
    mac_address varchar(255),
    model varchar(255) not null,
    serial_number varchar(255),
    type_device varchar(255) not null,
    user_id bigint,
    primary key (id)
);

create table parameter (
    id bigint generated by default as identity,
    created_date timestamp,
    type varchar(255),
    device_id bigint,
    primary key (id)
);

create table parameter_values (
    id bigint generated by default as identity,
    created_date timestamp,
    value double,
    parameter_id bigint,
    primary key (id)
);

create table roles (
    id bigint generated by default as identity,
    created_date timestamp,
    status varchar(255),
    last_modified_date timestamp,
    name varchar(255),
    user_id bigint,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    created_date timestamp,
    status varchar(255),
    last_modified_date timestamp,
    email varchar(255),
    first_name varchar(25),
    last_name varchar(25),
    password varchar(255),
    phone varchar(255),
    username varchar(25),
    primary key (id)
);

alter table devices
    add constraint UK_mac_address unique (mac_address);

alter table devices
    add constraint UK_serial_number unique (serial_number);

alter table devices
    add constraint devices_user_fk
    foreign key (user_id) references users;

alter table parameter
    add constraint parameter_device_fk
    foreign key (device_id) references devices;

alter table parameter_values
    add constraint parameter_values_parameter_fk
    foreign key (parameter_id) references parameter;

alter table roles
    add constraint roles_user_fk
    foreign key (user_id) references users;