package by.tms.diplomrestc51.enums;

public enum TypeParameter {
    TEMPERATURE_C,
    TEMPERATURE_F,
    HUMIDITY_PERCENTAGE,
    SPEED_METER_PER_SECOND,
    SPEED_KILOMETER_PER_HOUR,
    SPEED_MILE_PER_HOUR,
    SPEED_CENTIMETER_PER_SECOND,
    PATH_LENGTH,
    SUPPLY_VOLTAGE,
    K_W_CONSUMPTION,
    WATER_CONSUMPTION,
}
